language: python
python:
- 3.6
env:
- PKG_NAME=limix HDF5_USE_FILE_LOCKING=FALSE
addons:
  apt:
    packages:
    - libffi-dev
    - libffi6
script:
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
notifications:
  email:
    recipients:
    - danilo.horta@pm.com
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: sGwbXCd43Hj7JffZ2RH2ua1YVYWN026pdMMxJzm7136XrzrXcnCIHBGfKAj0688f1LFAo8mzWR74sdFC8F2QKrYjQXvTfmyKW6MAmCyXn+8SWz/GprDA09HvjlcOB2d9/sbMMjuC92+5cLLc5dUVCkahiKhtaTA8ZI5VD2CYrlnAg/U/TrlShcACpd09tUP0D3eGU5w/qkTH91WuwHRkZWOZv6F/vonlFHm5TvbjiERtsvyRrmbdLuLNZVKmv5rWPpu3De+mEtGWqD/LyM+dynOS5E5m8B0vNlw1KxkYrI7tq6jJ7l99qTceUbn9Nxj/ufxaX7BeZm0T7Y9LxyPbWGV7L1x+n5yEW3StY9fTtEGBVDSk+nIrl1Bw8ytU2+GobS/iCRxl5dao1l3qU1nApx5DSDfM+eA1HTClDy4O8n/uu4JNQLgSyKjq8S19qPcHVUeBziBkkbzA7XfCUkk5uZtkwIrRFlO66o7dzzq6RUCJhaPafyo1DpfhmMgwpmesW/HvOOLvPlcxEUv56YqseILVIIAAo6na3fMGZvX17KL0N2cK7/9rO3aEeHKqcW43MtQsyhElomn9Mn53LTug1iH57xPxl2q3dP7UaY3QSAJlDTaKrltEbOzcts/gMTEAizCuBsayE4J8vVU6leSkqVTbPcfU6WcbVDRC+GwxL8M=
  on:
    tags: true
    repo: limix/limix
    branch: 2.0.x
    python: 3.6
