language: python
python: 3.6
env: HDF5_USE_FILE_LOCKING=FALSE URL=https://raw.githubusercontent.com/horta/ci/master
matrix:
  include:
    - os: linux
    - os: osx
# addons:
#   apt:
#     packages:
#       - libffi-dev
#       - libffi6
install:
  - bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis-matplotlib-fix.sh)
  - bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis-check-readme.sh)
  - bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis-py-min-deps.sh)
  - bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis-py-check-style.sh)
  - bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis-py-check-black.sh)
script:
  - bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis-py-dev-test.sh)
  - bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis-py-install-test.sh)
  - bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis-py-sdist-test.sh)
  - bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis-py-doctest.sh)
notifications:
  email:
    recipients:
      - danilo.horta@pm.me
    on_success: never
    on_failure: always
